#!/usr/bin/env python3
# The campaign's membership commitments: one digest per (grammar, operation, damage size, seed) cell,
# taken over that cell's raw CSV lines in file order. The aggregate reconciliations bind counts, and a
# balanced pair of edits inside one cell can preserve every count; the commitment binds the bytes of
# the cell's rows themselves, so any membership transfer, however counterbalanced, changes a digest.
# The committed file is archived beside the campaign and regenerated by the reproduction script from
# the fresh harness rerun, whose byte-identity with the archive it verifies first, so the commitments
# carry the harness run's authority rather than merely restating the file they audit.
#
# Usage: commit_r6.py <campaign csv> [output path]
#
# Deterministic and stdlib-only: lines are grouped by their first four fields, digests are SHA-256
# over the concatenated raw lines, newline included, and the output is sorted by cell key.

import hashlib
import sys

sys.dont_write_bytecode = True


def cell_commitments(csv_path):
    digests = {}
    with open(csv_path, "rb") as handle:
        header = handle.readline()
        assert header.startswith(b"grammar,"), header[:40]
        for raw in handle:
            fields = raw.decode("utf-8").split(",", 4)
            key = "|".join(fields[:4])
            digests.setdefault(key, hashlib.sha256()).update(raw)
    return {key: digest.hexdigest() for key, digest in digests.items()}


def main():
    if len(sys.argv) not in (2, 3):
        sys.exit("usage: commit_r6.py <campaign csv> [output path]")
    digests = cell_commitments(sys.argv[1])
    lines = [f"{digests[key]}  {key}" for key in sorted(digests)]
    body = "\n".join(lines) + "\n"
    if len(sys.argv) == 3:
        with open(sys.argv[2], "w", encoding="utf-8") as handle:
            handle.write(body)
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
