#!/usr/bin/env python3
"""Generates the XID_Start and XID_Continue code point tables from the Unicode Character Database.

Reads DerivedCoreProperties.txt, published at https://www.unicode.org/Public/<version>/ucd/, and emits the
xid_ranges.inc file included by libs/regex/src/unicode.cpp. The generated file is checked in, so building munch
never touches the network; rerun this script against a newer database to move the pinned Unicode version.

Usage: tools/unicode/generate_xid.py <DerivedCoreProperties.txt> [output.inc]
"""

import hashlib
import re
import sys
from pathlib import Path


def parse_ranges(lines: list[str], property_name: str) -> list[tuple[int, int]]:
    """Extracts the sorted, merged code point ranges holding the given property."""
    pattern = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*" + property_name + r"\s*#")

    ranges = []

    for line in lines:
        if match := pattern.match(line):
            first = int(match.group(1), 16)
            last = int(match.group(2), 16) if match.group(2) else first

            if not first <= last <= 0x10FFFF:
                raise ValueError(f"invalid range {first:X}..{last:X}")

            ranges.append((first, last))

    ranges.sort()

    merged = [ranges[0]]

    for first, last in ranges[1:]:
        if first <= merged[-1][1]:
            raise ValueError(f"overlapping range {first:X}..{last:X}")

        if first == merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], last)
        else:
            merged.append((first, last))

    return merged


def emit_array(name: str, ranges: list[tuple[int, int]]) -> str:
    entries = "\n".join(f"        {{.first = 0x{first:X}, .last = 0x{last:X}}}," for first, last in ranges)

    return (
        f"constexpr std::array<Code_point_range, {len(ranges)}> {name}{{{{\n{entries}\n}}}};\n"
    )


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)

    raw = Path(sys.argv[1]).read_bytes()

    source = raw.decode("utf-8").splitlines()

    output = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parents[2] / "libs/regex/src/xid_ranges.inc")

    version_match = re.match(r"# DerivedCoreProperties-(\d+\.\d+\.\d+)\.txt", source[0])
    if not version_match:
        raise ValueError("first line does not name the database version")
    version = version_match.group(1)

    xid_start = parse_ranges(source, "XID_Start")
    xid_continue = parse_ranges(source, "XID_Continue")

    # Every XID_Start code point continues an identifier too; the stability guarantee behind that is what makes
    # the XID properties the identifier-defining pair, so a database violating it must not generate.
    continue_set = set()
    for first, last in xid_continue:
        continue_set.update(range(first, last + 1))
    for first, last in xid_start:
        if not all(point in continue_set for point in range(first, last + 1)):
            raise ValueError("XID_Start escapes XID_Continue")

    header = (
        f"// Generated by tools/unicode/generate_xid.py from DerivedCoreProperties-{version}.txt; do not edit.\n"
        f"// Source: https://www.unicode.org/Public/{version}/ucd/DerivedCoreProperties.txt\n"
        f"// Source SHA-256: {hashlib.sha256(raw).hexdigest()}\n"
        "// The ranges derive from the Unicode Character Database, (c) Unicode, Inc., used under the Unicode\n"
        "// License v3 (https://www.unicode.org/license.txt).\n"
        "\n"
        f'constexpr std::string_view unicode_version{{"{version}"}};\n'
        "\n"
    )

    output.write_text(
        header + emit_array("xid_start_ranges", xid_start) + "\n" + emit_array("xid_continue_ranges", xid_continue),
        encoding="utf-8",
        newline="\n",
    )

    start_points = sum(last - first + 1 for first, last in xid_start)
    continue_points = sum(last - first + 1 for first, last in xid_continue)

    print(f"Unicode {version}: XID_Start {len(xid_start)} ranges ({start_points} code points), "
          f"XID_Continue {len(xid_continue)} ranges ({continue_points} code points) -> {output}")


if __name__ == "__main__":
    main()
